language: php
php:
  - 7.0
sudo: false
env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1
install:
  - phpize
  - CFLAGS="-Wall -fno-strict-aliasing" ./configure --with-yaml
  - make all
script: TEST_PHP_EXECUTABLE=$(which php) php -n
    -d open_basedir= -d output_buffering=0 -d memory_limit=-1
    run-tests.php -n
    -d extension_dir=modules -d extension=yaml.so --show-diff
    tests
